# Generated by Django 4.2 on 2026-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lecture_video_url_section_lecture_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste image URL instead of upload')),
                ('action_type', models.CharField(choices=[('none', 'No Action'), ('course', 'Navigate to Course'), ('batch', 'Navigate to Batch')], default='none', max_length=50)),
                ('action_id', models.IntegerField(blank=True, help_text='ID of course or batch to open', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='payment_method',
            field=models.CharField(default='Direct', max_length=50),
        ),
    ]
